### ISSUE TITLE
Readme에 시연이 있으면 좋을것같아요 

### ISSUE THREAD

**Issue by arthur-yoon** [hbcha0916/QuickSearch#1]
커리어리에서 보고 구경을 왔어요. 좋은 컨셉의 유틸리티같아요. 유입자들이 한번에 효용을 알 수 있게 as-is, to-be 로 gif같은 동작을 첨부하면 어떨까요

**Comment by hbcha0916** [comment]
관심가져주셔서 감사합니다!  as-is, to-be 와 gif 이미지변환 방법을 배워 적용해 보겠습니다!





-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023-06-15 (목) 08:39:10 (GMT+09:00)
Subject: [hbcha0916/QuickSearch] Readme에 시연이 있으면 좋을것같아요 (Issue #1)

커리어리에서 보고 구경을 왔어요. 좋은 컨셉의 유틸리티같아요. 유입자들이 한번에 효용을 알 수 있게 as-is, to-be 로 gif같은 동작을 첨부하면 어떨까요

**Comment by arthur-yoon** [comment]
리드미 보니 수정하신거같군요~ 클로즈하겠습니당
